### ISSUE TITLE
Doesn't filter on project_id

### ISSUE THREAD

**Issue by MarkLyck** [zentered/vercel-preview-url#137]
I have multiple Vercel projects that gets deployed from the same GitHub Repo whenever a pull request is made.

This action gives me a vercel URL correctly, but it gives me a random one of the 3 vercel projects I have tied to my Github Repo.

This happens even though I have specified a project id.

```
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.0.0
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: prj_xxx
          vercel_team_id: xxx
```

When specifying a project_id I would expect it to ONLY resolve the URL for that given project and not another random project.
