### ISSUE TITLE
`branch_alias` not showing up among outputs

### ISSUE THREAD

**Issue by bkrmendy** [zentered/vercel-preview-url#169]
**Describe the bug**
`steps.vercel_preview_url.outputs.branch_alias` doesn't show up among the outputs for my project.

**To Reproduce**
Run the following GH action workflow with a Vercel project.
```
name: Find branch alias

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    e2e:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30 
            - name: vercel-preview-url
              uses: zentered/vercel-preview-url@v1.1.9
              id: vercel_preview_url
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
            - name: branch editor url
              run: echo "https://${{ steps.vercel_preview_url.outputs.branch_alias }}"
            
```

**Expected behavior**
The final echo should echo `https://<BRANCH_ALIAS>`. Instead, it's only `https://`

**Additional context**
The workflow run logs that it found 4 matching deployments. Maybe not all deployments have the branch alias?
