### ISSUE TITLE
Github is suddenly failing with Forbidden issues and wrong scope

### ISSUE THREAD

**Issue by Zelig880** [zentered/vercel-preview-url#170]
**Describe the bug**
The Github action stopped working all all of a sudden with no code changes. I expect this to be some changes in internal dependencies (eg vercel API).

The Gihub Action Fails with error: 
```
{
  "error": {
    "code": "forbidden",
    "message": "Not authorized: Trying to access resource under scope \"zelig880s-projects\". You must re-authenticate to this scope or use a token with access to this scope.",
    "saml": true,
    "teamId": null,
    "scope": "zelig880s-projects",
    "enforced": false
  }
}
``` 
What is important is that:
- All Environments are well set as the Action worked fine for over a year
- I have updated the Token and double checked the Project ID
- The "scope" shown above is actually incorrect. The vercel token has a different scope, but it is showing my "default" project as the scope.

**To Reproduce**

```
name: CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  eslint-and-format:
    runs-on: ubuntu-latest

    env:
      # Vercel Automation Bypass Secret, so that Playwright can access the Vercel deployment
      VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
      ENVIRONMENT: ${{ github.event_name == 'pull_request' && 'preview' || 'production' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.11.0
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Set up Vercel private registry
        run: pnpm config set //vercel-private-registry.vercel.sh/:_authToken $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.4.0
        id: vercel_preview_url
        if: github.event_name != 'pull_request'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_REF: "main"
          GITHUB_REPOSITORY: "PatrickHeneise/vercel-preview-action-test"
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
```

**Expected behavior**
The Github Action should run and I should get access to the Deployed URL

**Additional context**
Full error:

```
Run zentered/vercel-preview-url@v1.4.0
  with:
    vercel_project_id: ***
  env:
    VERCEL_AUTOMATION_BYPASS_SECRET: ***
    ENVIRONMENT: production
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    VERCEL_TOKEN: ***
    GITHUB_REF: main
    GITHUB_REPOSITORY: PatrickHeneise/vercel-preview-action-test
Retrieving deployment preview for apollo/develop
Fetching from: https://api.vercel.com/v6/deployments?projectId=***
Error: {
  "error": {
    "code": "forbidden",
    "message": "Not authorized: Trying to access resource under scope \"zelig880s-projects\". You must re-authenticate to this scope or use a token with access to this scope.",
    "saml": true,
    "teamId": null,
    "scope": "zelig880s-projects",
    "enforced": false
  }
}
Error: no deployments found
    at getDeploymentUrl (file:///home/runner/work/_actions/zentered/vercel-preview-url/v1.4.0/dist/index.js:38010:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///home/runner/work/_actions/zentered/vercel-preview-url/v1.4.0/dist/index.js:3563[2](https://github.com/KnopmanMarks/apollo/actions/runs/13390803488/job/37398312912#step:11:2):47
```
