### ISSUE TITLE
What do you do when deployments return 0

### ISSUE THREAD

**Issue by cohesivejones** [zentered/vercel-preview-url#171]
Its seems like there is a chicken and egg problem here. When this task runs we need the preview environment to be deployed, you reference using UnlyEd/github-action-await-vercel to wait for the deployment to be in the READY state, but that actionn requires a deployment URL that we get from this action. 

So how do we wait in a github action to call this action?

```
name: Cypress Tests on Vercel Preview

on: [deployment_status]

jobs:
  cypress-run:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up project
        uses: ./.github/actions/setup-project

      - run: sleep 30
      - name: Wait for Vercel Preview URL with App Name
        id: vercel_preview_url_by_name
        uses: zentered/vercel-preview-url@v1.4.0
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id:  ${{ secrets.VERCEL_TEAM_ID }}

      - name: Get Preview URL
        run: echo "https://${{
          steps.vercel_preview_url_by_name.outputs.preview_url}}"

      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_BASE_URL: 'https://${{ steps.vercel_preview_url_by_name.outputs.preview_url}}'
          CYPRESS_VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        with:
          working-directory: web-app/
```
